version: 0.2

phases:
  install:
    runtime-versions:
      java: nodejs12
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo No build yet
  post_build:
    commands:
      - echo Build completed on `date`
